# dotnet pack and publish to github package registry
name: Build and Publish NuGet Package
on:
  push:
    branches:
      - main
jobs:
  build:
    permissions:
      contents: read
      packages: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Copy readme
        run: cp README.md ./HarinkLib/README.md
      - name: Build solution
        run: dotnet build --configuration Release -p:Version=$(date +'%Y.%m.%d')-$(echo $GITHUB_SHA | cut -c1-7)
      - name: Run tests
        run: dotnet test --no-build --configuration Release --verbosity normal
      - name: Pack NuGet package
        run: dotnet pack --no-build --configuration Release --output ./artifacts -p:Version=$(date +'%Y.%m.%d')-$(echo $GITHUB_SHA | cut -c1-7)
      - name: Publish to GitHub Package Registry
        run: |
          dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/rikharink/index.json"
          dotnet nuget push ./artifacts/*.nupkg --source "github" --skip-duplicate